name: flutter_map_marker_popup_example
description: Example for Flutter Map Marker Popups.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

  latlong2: ^0.8.0
  flutter_map: ">=1.0.0 <2.0.0"
  flutter_map_marker_popup:
    path: ../

flutter:
  uses-material-design: true
  fonts:
    - family: AccurateMapIcon
      fonts:
        - asset: fonts/AccurateMapIcon.ttf

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter
