name: flutter_map_marker_popup_example
description: Example for Flutter Map Marker Popups.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  latlong2: ^0.8.0
  flutter_map: ^4.0.0
  flutter_map_marker_popup:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: AccurateMapIcon
      fonts:
        - asset: fonts/AccurateMapIcon.ttf
