name: flutter_map_marker_popup
description: A plugin for flutter_map to show a customisable popup Widget when a marker is tapped. Also provides methods to show/hide popups.
version: 5.1.0
homepage: https://github.com/rorystephenson/flutter_map_marker_popup

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  animated_stack_widget: ^0.0.4
  flutter_map: ^4.0.0
  latlong2: ^0.8.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
