name: flutter_map_marker_popup
description: Marker popups for flutter_map.
version: 6.1.2
homepage: https://github.com/rorystephenson/flutter_map_marker_popup
topics:
  - flutter-map
  - popups

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  animated_stack_widget: ^0.0.4
  flutter_map: ^7.0.0
  latlong2: ^0.9.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
